site_name: Harrison's Guide to Lifeguarding
site_author: Harrison Goeldner
site_url: https://lifeguard.guide

# Repository
repo_url: https://github.com/harrisongoeldner/lifeguarding-guide
repo_name: lifeguarding-guide

# CSS overrides
extra_css:
  - stylesheets/extra.css

# Custom variables
extra:
  homepage: https://lifeguard.guide

# Navigation
nav:
  - Home: index.md
  - Lifeguarding:
    - lifeguarding/index.md
    - Priority Action Approach:
      - At a Glance: lifeguarding/priority-action-approach/at-a-glance.md
      - Scene Survey: lifeguarding/priority-action-approach/scene-survey.md
      - Primary Survey: lifeguarding/priority-action-approach/primary-survey.md
      - Seconary Survey: lifeguarding/priority-action-approach/secondary-survey.md
      - Critical Inteventions: lifeguarding/priority-action-approach/critical-interventions.md
    - Oxygen Administration: lifeguarding/oxygen-administration.md
  - Teaching Swimming:
    - teaching-swimming/index.md

# Theme
theme: 
  name: material
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.expand
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
  palette:
  
    # Palette toggle for auto mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Follow system preferences

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: 'black'

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      
# Copyright
copyright:
  Copyright &copy; 2024 Harrison Goeldner –
  <a href="#__consent">Change cookie settings</a>

#Extensions
markdown_extensions:
  - toc: 
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - privacy
  - search
  - blog
  - social
